### ISSUE TITLE
没检测到

### ISSUE THREAD

**Issue by albb762** [passerby-b/douyin_record#1]
默认的房间有1个可以，我自己的不行，能写个具体使用说明吗

**Comment by passerby-b** [comment]
哪个房间号,我试试

**Comment by albb762** [comment]
"name":"野鹭户外",
        "roomid":7151359804120976166
       房间id是抖音分享链接复制到浏览器打开以后的数字。好像比你那个长。

**Comment by passerby-b** [comment]
你这id不对,用网页版打开直播间复制网址最后面的数字id,例如https://live.douyin.com/905356464391

**Comment by albb762** [comment]
可以了，谢谢

**Comment by albb762** [comment]
可以了，谢谢
